### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by cbiqih** [shanahanjrs/xmltojson#3]
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmltojson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xmltojson.py", line 23, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'

**Comment by gregmoncayo** [comment]
Did you find the solution to this issue?

**Comment by spookyahell** [comment]
How come this was closed?!
The underlying issue hasn't been fixed yet.

But to answer @gregmoncayo, yes it's fixable and the fix is rather simple.
The project is missing a `utils.py` file in the project's root directory** with the line:
```
__version__ = '2.0.1'
```

** `site-packages`, somewhere on the machine you are using.
For Windows OS usually here
`C:\Users\<USER>\AppData\Roaming\Python\Python39\site-packages\xmltojson`
(Replace ´`<USER>` with the appropriate value)

Ok, now: If that's all you changed you should still be getting an error.

_Speaking as a learner and python "beginner", you'd think by version 3.9 python could be smart enough to auto-search the root directory of a python package for a file if it can't find it in the cwd ("current working directory"). But No._

So, what you'll need to do in `__init__.py` is:
change the line
```python
import utils
```
to the proper way to import the file
```python
from . import utils
```
(This will refer to the dir of current file)

Ok, so far so good. Now we get the same error for another file.

Instead of `import utils` make the corresponding line in `scripts/cli.py` say this
 ```python
from .. import utils
```
(This will refer to the parent dir of current file)

**Comment by rjurney** [comment]
I can't use `xmltojson` because of this error message. Why was the issue closed?
